Remove KDE mentions
PrivSec-dev/privsec.dev pull request #267
Opened 2024-07-29 20:18 UTC by TommyTran732

Only GNOME should be recommended.

2024-07-30 14:53 UTC, friendly-rabbit-35 requested changes

2024-07-30 14:53 UTC, friendly-rabbit-35 commented on content/posts/linux/Choosing Your Desktop Linux Distribution/index.md
> +You should use GNOME as your desktop environment. It supports [Wayland](https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)) and implements permission control for privileged Wayland proto
```suggestion
You should use GNOME as your desktop environment. It supports [Wayland](https://en.wikipedia.org/wiki/Wayland_(display_server_protocol)), a display protocol developed with security [in mind](https://lwn.net/Articles/589147), and implements permission control for privileged Wayland protocols like screencopy. There are other desktop environments and window managers with Wayland support, but I am not aware of any permission control implemented by them.
```
I also suggest embedding a link to a relevant merge request or issue about the permission control mentioned here.

Not suggesting this link necessarily, but just something I found that might be relevant: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970

2024-07-30 14:53 UTC, friendly-rabbit-35 commented on content/posts/linux/Choosing Your Desktop Linux Distribution/index.md
> +Wayland's predecessor, [X11](https://en.wikipedia.org/wiki/X_Window_System), does not support GUI isolation, allowing all windows to [record screen, log and inject inputs in other windows](https://bl
```suggestion
Wayland's predecessor, [X11](https://en.wikipedia.org/wiki/X_Window_System), does not support GUI isolation, allowing all windows to [record screen, log and inject inputs in other windows](https://blog.invisiblethings.org/2011/04/23/linux-security-circus-on-gui-isolation.html), making any attempt at sandboxing futile. While there are options to run nested X11 sessions such as [Xpra](https://en.wikipedia.org/wiki/Xpra) or [Xephyr](https://en.wikipedia.org/wiki/Xephyr), they often come with negative performance consequences, are not convenient to set up, and are not preferable to Wayland. You should avoid desktop environments and window managers which only support X11.
```

2024-07-30 14:53 UTC, friendly-rabbit-35 commented on content/posts/linux/Choosing Your Desktop Linux Distribution/index.md
> +[Fedora Silverblue](https://silverblue.fedoraproject.org/) is an immutable variants of Fedora with a strong focus on container workflows. It follows the same release schedule as Fedora Workstation, b
```suggestion
[Fedora Silverblue](https://silverblue.fedoraproject.org/) is an immutable variant of Fedora with a strong focus on container workflows. It follows the same release schedule as Fedora Workstation, benefiting from the same fast updates and staying very close to upstream.
```

2024-07-30 18:32 UTC, MorsMortium commented
What kind of permission control?
KDE wayland with pipewire has these:
![Screenshot_20240730_201654](https://github.com/user-attachments/assets/5a66096e-4030-4a24-be12-e62baab977b8)
![Screenshot_20240730_201713](https://github.com/user-attachments/assets/d47b7382-fd6b-49bd-b988-fc24828dfed7)
Without the user clicking them, the app can't access the screen/window.

2024-07-30 20:52 UTC, TommyTran732 commented
@MorsMortium

Can you check with Flameshot? I am pretty sure @qoijjj tested it and there isn't any prompt

2024-07-30 20:56 UTC, qoijjj commented
@TommyTran732 when I tested it, I was able to capture the screen by layering `flameshot` on kinoite, yes. With no prompt

what @MorsMortium shared looks like the wayland screenshare popup, which as far as I know is unrelated to the wl screencopy protocol

2024-07-30 20:57 UTC, qoijjj commented
@MorsMortium if you are unable to repro, that would be very interesting

2024-07-30 21:11 UTC, MorsMortium commented
Yeah, these are for screen sharing. Didn't know screen copy was something else. Both spectacle and flameshot can make screenshots

2024-08-01 05:17 UTC, merged

2024-08-06 17:42 UTC, jermanuts commented
https://discuss.privacyguides.net/t/people-should-avoid-wayland-environments-which-use-wlroots-as-the-compositor/17899/8

2024-08-06 18:01 UTC, qoijjj commented
@jermanuts I responded on the thread