AppVerifier and Obtainium exist
PrivSec-dev/privsec.dev pull request #282
Opened 2024-10-12 04:40 UTC by randomwithnoname

2024-10-22 02:59 UTC, wj25czxj47bu6q commented
@randomwithnoname For this PR we would like you to please [review and accept our Contributor License Agreement](https://github.com/PrivSec-dev/contributor-license-agreement).

2024-10-22 03:02 UTC, wj25czxj47bu6q requested changes

2024-10-22 03:02 UTC, wj25czxj47bu6q commented on content/posts/android/F-Droid Security Issues.md
> +F-Droid is often seen as the only way to get and support open-source apps: that is not the case. Sure, F-Droid could help you in finding FOSS apps that you wouldn't otherwise have known existed. Many
While mentioning Obtainium and AppVerifier would be a great addition, I think we should mention them _in addition_ to the Atom feed and `apksigner` that were already mentioned.

2024-10-22 23:02 UTC, randomwithnoname commented
I accept
https://github.com/PrivSec-dev/contributor-license-agreement/issues/8

2024-10-28 19:10 UTC, wj25czxj47bu6q commented
> I accept [PrivSec-dev/contributor-license-agreement#8](https://github.com/PrivSec-dev/contributor-license-agreement/issues/8)

Thanks. Please work on incorporating the aforementioned feedback so we can merge this.

2024-10-30 22:07 UTC, randomwithnoname commented
Moved to https://github.com/PrivSec-dev/privsec.dev/pull/289

2024-10-30 22:07 UTC, closed without merging