Windows Overview
PrivSec-dev/privsec.dev pull request #287
Opened 2024-10-26 05:14 UTC by oppressor1761

including security and privacy overview.

2024-10-28 19:19 UTC, wj25czxj47bu6q commented
@oppressor1761 We would like you to please [review and accept our Contributor License Agreement](https://github.com/PrivSec-dev/contributor-license-agreement) for this PR.

2024-10-28 19:23 UTC, wj25czxj47bu6q requested changes
Some of this is good, but some of it is questionable or insufficiently explained.

For example, why should optional diagnostic data be allowed?

Also, we are not going to accept any commands or instructions regarding activation. It is fine to recommend specific editions of Windows, but that's about it.

2025-04-08 10:32 UTC, nihil-admirari commented
In-depth analysis of Windows architecture and telemetry: https://www.bsi.bund.de/EN/Service-Navi/Publikationen/Studien/SiSyPHuS_Win10/SiSyPHuS_node.html. Some worthy mentions:
- [Analysis of Windows 10 - OS Architecture](https://www.bsi.bund.de/EN/Service-Navi/Publikationen/Studien/SiSyPHuS_Win10/AP2/SiSyPHuS_AP2_node.html) (all in English except the introduction)
- [Analysis of Telemetry](https://www.bsi.bund.de/EN/Service-Navi/Publikationen/Studien/SiSyPHuS_Win10/AP4/SiSyPHuS_AP4_node.html) (analysis in English except the introduction, configuration in German)

They recommend making a hard link for `svchost.exe`, changing `DiagTrack` to use that hardlink, and then blocking harklink's access to internet using built-in firewall.

A more hardcore version would be to change Windows Update service to use the hardlink and block all outbound completely, with the exception of Windows Update.

2025-07-17 15:26 UTC, nihil-admirari commented
Back in 2012, Windows used [**non-validating** DNSSEC aware local resolver](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn593685(v=ws.11)). Have things improved since then? Should I run Unbound locally or in a Linux VM (like with chrony) to do DNSSEC validation?

2025-07-25 05:51 UTC, oppressor1761 commented
I think it's better to harden Windows using lgpo, .ppkg and answer files rather than alter group policies one by one manually. It's not easy to remember every custom policies you ever applied without a lgpo.
I have audited the most of Windows group policies and already built my own lgpo.txt guide. However I'm not sure how to explain every items in it cause it contains hundreds of items.

2025-07-25 08:09 UTC, nihil-admirari commented
LGPO text files support comments, e.g.:
```ini
; \Control Panel\Personalization
; Prevent enabling lock screen camera
; Enabled
Computer
Software\Policies\Microsoft\Windows\Personalization
NoLockScreenCamera
DWORD:1
```

2025-07-25 12:36 UTC, oppressor1761 commented
this lgpo can be applied without caution.
```
; LGPO-text file, used with LGPO.exe.

; Smart App Control
Computer
SYSTEM\CurrentControlSet\Control\CI\Policy
VerifiedAndReputablePolicyState
DWORD:1

; Choose drive encryption method and cipher strength (Windows 10 [Version 1511] and later)
Computer
SOFTWARE\Policies\Microsoft\FVE
EncryptionMethodWithXtsOs
DWORD:7

; Choose drive encryption method and cipher strength (Windows 10 [Version 1511] and later)
Computer
SOFTWARE\Policies\Microsoft\FVE
EncryptionMethodWithXtsFdv
DWORD:7

; Choose drive encryption method and cipher strength (Windows 10 [Version 1511] and later)
Computer
SOFTWARE\Policies\Microsoft\FVE
EncryptionMethodWithXtsRdv
DWORD:4

; Require additional authentication at startup
Computer
SOFTWARE\Policies\Microsoft\FVE
UseAdvancedStartup
DWORD:1

; Require additional authentication at startup
Computer
SOFTWARE\Policies\Microsoft\FVE
EnableBDEWithNoTPM
DWORD:0

; Require additional authentication at startup
Computer
SOFTWARE\Policies\Microsoft\FVE
UseTPMKey
DWORD:2

; Require additional authentication at startup
Computer
SOFTWARE\Policies\Microsoft\FVE
UseTPMPIN
DWORD:2

; Require additional authentication at startup
Computer
SOFTWARE\Policies\Microsoft\FVE
UseTPMKeyPIN
DWORD:2

; Require additional authentication at startup
Computer
SOFTWARE\Policies\Microsoft\FVE
UseTPM
DWORD:2

; Disallow standard users from changing the PIN or password
Computer
SOFTWARE\Policies\Microsoft\FVE
DisallowStandardUserPINReset
DWORD:1

; Interactive logon: Don't display last signed-in
Computer
Software\Microsoft\Windows\CurrentVersion\Policies\System
DontDisplayLastUserName
DWORD:1

; Interactive logon: Don’t display username at sign-in
Computer
Software\Microsoft\Windows\CurrentVersion\Policies\System
DontDisplayUserName
DWORD:1

; Interactive logon: Machine account lockout threshold
Computer
Software\Microsoft\Windows\CurrentVersion\Policies\System
MaxDevicePasswordFailedAttempts
DWORD:10

; Interactive logon: Do not require CTRL+ALT+DEL
Computer
Software\Microsoft\Windows\CurrentVersion\Policies\System
DisableCAD
DWORD:0

; Do not display network selection UI
Computer
Software\Policies\Microsoft\Windows\System
DontDisplayNetworkSelectionUI
DWORD:1

; Network access: Remotely accessible registry paths
Computer
System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedExactPaths
Machine
MULTISZ:

; Network access: Remotely accessible registry paths and sub-paths
Computer
System\CurrentControlSet\Control\SecurePipeServers\Winreg\AllowedPaths
Machine
MULTISZ:

; Enable Certificate Padding
Computer
Software\Microsoft\Cryptography\Wintrust\Config
EnableCertPaddingCheck
DWORD:1

; Enable Certificate Padding
Computer
Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config
EnableCertPaddingCheck
DWORD:1

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
56a863a9-875e-4185-98a7-b882c64b5ce5
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
d4f940ab-401b-4efc-aadc-ad5f3c50688a
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
be9ba2d9-53ea-4cdc-84e5-9b1eeee46550
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
01443614-cd74-433a-b99e-2ecdc07bfc25
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
5beb7efe-fd9a-4556-801d-275e5ffc04cc
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
d3e037e1-3eb8-44c8-a917-57927947596d
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
3b576869-a4ec-4529-8536-b80a7769e899
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
26190899-1602-49e8-8b27-eb1d0a1ce869
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
e6db77e5-3df2-4cf1-b95a-636979351e5b
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
d1e49aac-8f56-4280-b9ba-993a6d77406c
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
33ddedf1-c6e0-47cb-833e-de6133960387
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
c0033c00-d16d-4114-a5a0-dc9b3a7d2ceb
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
a8f5898e-1dc8-49a9-9878-85004b8a61e6
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
92e97fa1-2edf-4476-bdd6-9dd0b4dddc7b
SZ:6

; Configure Attack Surface Reduction rules
Computer
Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
c1db55ab-c21a-4637-bb3f-a12568109d35
SZ:6

; KB5032314
Computer
SOFTWARE\Microsoft\Ole\AppCompat\OLELinkConversionFromOLESTREAMToIStorage
Disabled
DWORD:1

; Allow Diagnostic Data
Computer
Software\Policies\Microsoft\Windows\DataCollection
AllowTelemetry
DWORD:0

; Accounts: Block Microsoft accounts
Computer
Software\Microsoft\Windows\CurrentVersion\Policies\System
NoConnectedUser
DWORD:1

; Allow Cortana
Computer
SOFTWARE\Policies\Microsoft\Windows\Windows Search
AllowCortana
DWORD:0

; Allow Cloud Search
Computer
SOFTWARE\Policies\Microsoft\Windows\Windows Search
AllowCloudSearch
DWORD:0

; Allow search and Cortana to use location
Computer
SOFTWARE\Policies\Microsoft\Windows\Windows Search
AllowSearchToUseLocation
DWORD:0

; Do not allow web search
Computer
SOFTWARE\Policies\Microsoft\Windows\Windows Search
DisableWebSearch
DWORD:1

; Don't search the web or display web results in Search
Computer
SOFTWARE\Policies\Microsoft\Windows\Windows Search
ConnectedSearchUseWeb
DWORD:0

; Do not show Windows tips
Computer
Software\Policies\Microsoft\Windows\CloudContent
DisableSoftLanding
DWORD:1

; Turn off cloud consumer account state content
Computer
Software\Policies\Microsoft\Windows\CloudContent
DisableConsumerAccountStateContent
DWORD:1

; Turn off cloud optimized content
Computer
Software\Policies\Microsoft\Windows\CloudContent
DisableCloudOptimizedContent
DWORD:1

; Do not use diagnostic data for tailored experiences
User
Software\Policies\Microsoft\Windows\CloudContent
DisableTailoredExperiencesWithDiagnosticData
DWORD:1

; Turn off the Windows Welcome Experience
User
Software\Policies\Microsoft\Windows\CloudContent
DisableWindowsSpotlightWindowsWelcomeExperience
DWORD:1

; Turn off all Windows spotlight features
User
Software\Policies\Microsoft\Windows\CloudContent
Disabl [...]

2025-07-25 12:37 UTC, oppressor1761 commented
This lgpo must be applied with caution
```
; LGPO-text file, used with LGPO.exe.

; Disable new DMA devices when this computer is locked. Endabled in the Baseline. need to be disabled when DMA Protection is on.
Computer
Software\Policies\Microsoft\FVE
DisableExternalDMAUnderLock
DELETE

; Secured-core PC
Computer
SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios
SecureBiometrics
DWORD:1

; Secured-core PC
Computer
SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios
SecureFingerprint
DWORD:1

; KB4073119
Computer
SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
FeatureSettingsOverrideMask
DWORD:3

; KB4073119
Computer
SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization
MinVmVersionForCpuBasedMitigations
SZ:1.0

; KB4073119
Computer
SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization
RetsPredictedFromRsbOnly
DWORD:1

; KB4073119 Intel SMT
Computer
SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
FeatureSettingsOverride
DWORD:0x00800048

; KB4073119 Intel w/o SMT
Computer
SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
FeatureSettingsOverride
DWORD:0x00802048

; KB4073119 AMD
Computer
SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
FeatureSettingsOverride
DWORD:0x05000048

; KB4073119 ARM
Computer
SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
FeatureSettingsOverride
64

; Require UEFI Memory Attributes Table
Computer
SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
HVCIMATRequired
DWORD:0

; Machine Identity Isolation
Computer
SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
MachineIdentityIsolation
DWORD:2

; VBS (and memory integrity) in mandatory mode
Computer
SYSTEM\CurrentControlSet\Control\DeviceGuard
Mandatory
DWORD:1

; VBS with UEFI lock
Computer
SYSTEM\CurrentControlSet\Control\DeviceGuard
Locked
DWORD:1

; ActivePolicyCode
Computer
SOFTWARE\Microsoft\Windows\CurrentVersion\DeviceAccess
ActivePolicyCode
SZ:zh

; Intel TDT Integration Level
Computer
Software\Policies\Microsoft\Windows Defender\Features
TDTFeatureEnabled
DWORD:1

; Add workstations to domain
; delete all
```

2025-07-25 12:39 UTC, oppressor1761 commented
this is the answer file for arm64 devices
```
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="specialize">
        <component name="Microsoft-Windows-DeviceAccess" processorArchitecture="arm64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <SetRegionSpecificPrivacyAccessPolicy>zh</SetRegionSpecificPrivacyAccessPolicy>
        </component>
        <component name="Microsoft-Windows-ErrorReportingCore" processorArchitecture="arm64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <DisableWER>1</DisableWER>
        </component>
    </settings>
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="arm64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <OOBE>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
            </OOBE>
        </component>
    </settings>
</unattend>
```

2025-07-25 12:39 UTC, oppressor1761 commented
this is the provision package
```
<?xml version="1.0" encoding="utf-8"?>
<WindowsCustomizations>
  <PackageConfig xmlns="urn:schemas-Microsoft-com:Windows-ICD-Package-Config.v1.0">
    <ID>{c4a4a019-4fc1-4872-9ecd-83c966856d86}</ID>
    <Name>profile</Name>
    <Version>1.2</Version>
    <OwnerType>ITAdmin</OwnerType>
    <Rank>0</Rank>
    <Notes></Notes>
  </PackageConfig>
  <Settings xmlns="urn:schemas-microsoft-com:windows-provisioning">
    <Customizations>
      <Common>
        <CountryAndRegion>
          <CountryCodeForExtendedCapabilityPrompts>China</CountryCodeForExtendedCapabilityPrompts>
        </CountryAndRegion>
        <DeviceManagement>
          <MemoryDump>
            <AllowCrashDump>Not allowed</AllowCrashDump>
            <AllowLiveDump>Not allowed</AllowLiveDump>
          </MemoryDump>
        </DeviceManagement>
        <FederatedAuthentication>
          <EnableWebSignInForPrimaryUser>Disabled</EnableWebSignInForPrimaryUser>
        </FederatedAuthentication>
        <Licensing>
          <DisallowKMSClientOnlineAVSValidation>True</DisallowKMSClientOnlineAVSValidation>
        </Licensing>
        <OOBE>
          <Desktop>
            <EnableCortanaVoice>False</EnableCortanaVoice>
          </Desktop>
        </OOBE>
        <Policies>
          <AboveLock>
            <AllowToasts>No</AllowToasts>
          </AboveLock>
          <Bluetooth>
            <AllowAdvertising>No</AllowAdvertising>
            <AllowPrepairing>No</AllowPrepairing>
            <AllowPromptedProximalConnections>No</AllowPromptedProximalConnections>
          </Bluetooth>
          <DeviceManagement>
            <DisableMDMEnrollment>Yes</DisableMDMEnrollment>
          </DeviceManagement>
          <Experience>
            <AllowCortana>No</AllowCortana>
            <AllowFindMyDevice>No</AllowFindMyDevice>
            <AllowSyncMySettings>No</AllowSyncMySettings>
            <AllowTailoredExperiencesWithDiagnosticData>No</AllowTailoredExperiencesWithDiagnosticData>
            <DoNotShowFeedbackNotifications>Do not show</DoNotShowFeedbackNotifications>
          </Experience>
          <Games>
            <AllowAdvancedGamingServices>No</AllowAdvancedGamingServices>
          </Games>
          <MemoryDump>
            <AllowCrashDump>Not allowed</AllowCrashDump>
            <AllowLiveDump>Not allowed</AllowLiveDump>
          </MemoryDump>
          <Privacy>
            <AllowInputPersonalization>No</AllowInputPersonalization>
            <DisableAdvertisingId>Yes</DisableAdvertisingId>
          </Privacy>
          <Search>
            <AllowSearchHighlights>Disable</AllowSearchHighlights>
            <AllowSearchToUseLocation>No</AllowSearchToUseLocation>
            <DoNotUseWebResults>Prevent web search</DoNotUseWebResults>
            <PreventRemoteQueries>Yes</PreventRemoteQueries>
          </Search>
          <Start>
            <AllowPinnedFolderMusic>Enforced off</AllowPinnedFolderMusic>
            <AllowPinnedFolderPictures>Enforced off</AllowPinnedFolderPictures>
            <AllowPinnedFolderVideos>Enforced off</AllowPinnedFolderVideos>
            <HideFrequentlyUsedApps>Yes</HideFrequentlyUsedApps>
            <HideRecentJumplists>Yes</HideRecentJumplists>
            <HideRecentlyAddedApps>Yes</HideRecentlyAddedApps>
            <HideRecommendedSection>Yes</HideRecommendedSection>
            <ShowOrHideMostUsedApps>Hide</ShowOrHideMostUsedApps>
          </Start>
          <System>
            <AllowBuildPreview>Not allowed</AllowBuildPreview>
            <DisableOneDriveFileSync>Yes</DisableOneDriveFileSync>
            <LimitDiagnosticLogCollection>Enable Policy</LimitDiagnosticLogCollection>
            <LimitDumpCollection>Enable Policy</LimitDumpCollection>
            <LimitEnhancedDiagnosticDataWindowsAnalytics>Disable Windows Analytics collection</LimitEnhancedDiagnosticDataWindowsAnalytics>
            <TurnOffFileHistory>Turn off</TurnOffFileHistory>
          </System>
          <TextInput>
            <AllowIMELogging>No</AllowIMELogging>
            <AllowIMENetworkAccess>No</AllowIMENetworkAccess>
            <AllowKeyboardTextSuggestions>No</AllowKeyboardTextSuggestions>
            <AllowLinguisticDataCollection>No</AllowLinguisticDataCollection>
          </TextInput>
          <WiFi>
            <AllowAutoConnectToWiFiSenseHotspots>No</AllowAutoConnectToWiFiSenseHotspots>
          </WiFi>
          <WindowsAI>
            <DisableAIDataAnalysis>Disabled Data Analysis for Windows AI.</DisableAIDataAnalysis>
            <TurnOffWindowsCopilot>Disabled Windows Copilot</TurnOffWindowsCopilot>
          </WindowsAI>
          <WindowsInkWorkspace>
            <AllowSuggestedAppsInWindowsInkWorkspace>No</AllowSuggestedAppsInWindowsInkWorkspace>
          </WindowsInkWorkspace>
          <WindowsLogon>
            <DisableLockScreenAppNotifications>Enable this policy</DisableLockScreenAppNotifications>
            <EnableFirstLogonAnimation>No</EnableFirstLogonAnimation>
          </WindowsLogon>
        </Policies>
        <Privacy>
          <LetAppsActivateWithVoice>Force Deny</LetAppsActivateWithVoice>
          <LetAppsActivateWithVoiceAboveLock>Force Deny</LetAppsActivateWithVoiceAboveLock>
        </Privacy>
      </Common>
    </Customizations>
  </Settings>
</WindowsCustomizations>
```

2025-07-26 07:34 UTC, nihil-admirari commented
`unattend.xml` settings are for ARM only and contain local paths to `install.wim`:
```xml
<cpi:offlineImage cpi:source="wim:c:/users/gerbil1183/desktop/install.wim#Windows 11 Pro" xmlns:cpi="urn:schemas-microsoft-com:cpi" />
```

2025-12-13 20:08 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +[Secured-Core PCs](https://www.microsoft.com/en-us/windows/business/windows-11-secured-core-computers) ensure the hardware has some essential security [features](https://learn.microsoft.com/en-us/win
```suggestion
[Secured-core PCs](https://www.microsoft.com/en-us/windows/business/windows-11-secured-core-computers) ensure the hardware has some essential security [features](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-highly-secure-11#what-makes-a-secured-core-pc) including Secure Boot, Trusted Platform Module 2.0 (TPM), Direct Memory Access (DMA) Protection, Enhanced Sign-in Security (ESS), Virtualization-based Security (VBS) and System Guard Secure Launch with System Management Mode (SMM) isolation/Firmware Attack Surface Reduction (FASR). Microsoft Pluton and Total Memory Encryption are also good to have.
```

2025-12-13 20:09 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +[Secure Boot](https://learn.microsoft.com/en-us/windows/security/operating-system-security/system-security/trusted-boot) makes a safe and trusted path from the firmware to the Windows bootloader by m
```suggestion
[Secure Boot](https://learn.microsoft.com/en-us/windows/security/operating-system-security/system-security/trusted-boot) makes a safe and trusted path from the firmware to the Windows bootloader by making the firmware to examine the bootloader's digital signature to verify that it hasn't been modified. It may also allow drivers and applications from 3rd parties to run on the PC, which increases attack surface. You can disable Microsoft 3rd Party UEFI CAs (Microsoft Corporation UEFI CA 2011, Microsoft UEFI CA 2023) and Microsoft Option ROM CA (Microsoft Option ROM UEFI CA 2023) if you are not using a third party operating system. Trusted Boot, which is not a hardware feature, picks up the process started with Secure Boot. The Windows bootloader verifies the digital signature of the Windows kernel before loading it. The Windows kernel, in turn, verifies every other component of the Windows startup process, including boot drivers, startup files, and your anti-malware product's early-launch anti-malware (ELAM) driver. These mechanisms do not protect the firmware itself.
```

2025-12-13 20:10 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +[Trusted Platform Module 2.0 (TPM)](https://learn.microsoft.com/en-us/windows/security/hardware-security/tpm/trusted-platform-module-overview) is a secure crypto-processor that is designed to carry o
```suggestion
[Trusted Platform Module 2.0 (TPM)](https://learn.microsoft.com/en-us/windows/security/hardware-security/tpm/trusted-platform-module-overview) is a processor designed to carry out cryptographic operations. Some features rely on TPM: BitLocker, Windows Hello, and System Guard Secure Launch.
```

2025-12-13 20:11 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +[Microsoft Pluton](https://learn.microsoft.com/en-us/windows/security/hardware-security/pluton/microsoft-pluton-security-processor) is a secure crypto-processor built into the CPU to provide the func
```suggestion
[Microsoft Pluton](https://learn.microsoft.com/en-us/windows/security/hardware-security/pluton/microsoft-pluton-security-processor) is a processor built into the CPU to provide the functionality of the TPM and deliver security functionality beyond what is possible with the TPM 2.0 specification. It also allows for other Pluton firmware and OS features to be delivered over time via Windows Update.
```

2025-12-13 20:12 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +Most applications on Windows are not sandboxed. In Microsoft Store, only the apps without the permission “This app can access all your files, peripheral devices, apps, programs, and registry” are san
```suggestion
Most applications on Windows are not sandboxed. In Microsoft Store, only the apps without the permission “This app can access all your files, peripheral devices, apps, programs, and registry” are sandboxed. If you sideload apps, only those with the file extensions `.msix`, `.msixbundle`, `.appx`, and `.appxbundle` without the permission "This app can access all your files, peripheral devices, apps, programs, and registry" are sandboxed. If you are a developer or are technically skilled, you can deploy sandboxing to unsandboxed applications using [Win32 app isolation](https://learn.microsoft.com/en-us/windows/win32/secauthz/app-isolation-overview).
```

2025-12-13 20:13 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +You can also use [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview) to run untrusted apps. It pr
```suggestion
You can also use [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview) to run untrusted apps. It provides a lightweight virtual machine to isolate applications. You can transfer files and apps into Windows Sandbox by copying them.
```

2025-12-13 20:14 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +Windows include [Windows Security](https://support.microsoft.com/en-us/windows/stay-protected-with-windows-security-2ae0363d-0ada-c064-8b56-6a39afb6a963), which provides the latest antivirus protecti
```suggestion
Windows includes [Windows Security](https://support.microsoft.com/en-us/windows/stay-protected-with-windows-security-2ae0363d-0ada-c064-8b56-6a39afb6a963), which provides the latest anti-malware protection, system security settings, Exploit Protection and Controlled Folder Access. Some settings may not be changed in the UI if you have deployed security baselines.
```

2025-12-13 20:16 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +    Enable additional mitigations against silicon-based microarchitectural and speculative execution side-channel vulnerabilities in AMD processors by executing the following command from an elevated
```suggestion
    Enable additional mitigations against silicon-based microarchitectural and speculative execution side-channel vulnerabilities in AMD processors by executing the following command from an elevated command prompt. To further increase mitigations, you can also disable Hyper-Threading (also known as Simultaneous Multi Threading or SMT).
```

2025-12-13 20:17 UTC, Ganwtrs commented on content/posts/windows/Windows Overview.md
> +    Enable additional mitigations against silicon-based microarchitectural and speculative execution side-channel vulnerabilities in ARM processors by executing the following command from an elevated
```suggestion
    Enable additional mitigations against silicon-based microarchitectural and speculative execution side-channel vulnerabilities in ARM processors by executing the following command from an elevated command prompt. To further increase mitigations, you can also disable Hyper-Threading (also known as Simultaneous Multi Threading or SMT).
```

2026-01-30 13:47 UTC, closed without merging